Maya + Unreal Build scripts (Win/Linux)
ynput/ayon-usd-resolver pull request #15
Opened 2024-05-08 15:45 UTC by Lypsolon

im opening this pr to close the other Pr 
as this branch was created from the other branch and contains all the important work from it. 
this PR also serves to block further development from me until both plugins are fully working and tested for both Os setups. 

this PR implements 

- Unreal5_4 win + Linux (Ps: win is not well tested yet so assume fixes there)
- Maya24_4 win + linux (Ps: win is not well tested yet so assume fixes there)

2024-05-08 15:54 UTC, m-u-r-p-h-y commented
Is Ondra the only one to help here or can we test something from a user perspective as well? If so, we need some instructions :)

2024-05-08 15:59 UTC, Lyon-Rosenblatt-Ynput commented
> Is Ondra the only one to help here or can we test something from a user perspective as well? If so, we need some instructions :)

im not sure tbh right now. 
the main thing on this branch is resolver loading on the Usd side and the compile time linking errors that might be there on the windows side. 

currently there is no User perspective on this repo because the user interaction / server settings will be handled by the AyonUsd plugin. 

so im gonna answer that with an: im not sure.

2024-05-24 12:28 UTC, antirotor reviewed
Running `test/TestAyonUsd.bat`:

```
(base) PS C:\Users\annat\Documents\Projects\Ayon\ayon-usd-resolver> .\scripts\buildAyonUsd.bat

C:\Users\annat\Documents\Projects\Ayon\ayon-usd-resolver>REM in case you use Pyenv // Pyenv exec works

C:\Users\annat\Documents\Projects\Ayon\ayon-usd-resolver>cd ../

C:\Users\annat\Documents\Projects\Ayon>rmdir /s /q build
The system cannot find the file specified.

C:\Users\annat\Documents\Projects\Ayon>rmdir /s /q Resolvers/AyonUsdWin/AyonUsd23_5_py39
Invalid switch - "AyonUsdWin".

C:\Users\annat\Documents\Projects\Ayon>set AyonUsdRoot=

C:\Users\annat\Documents\Projects\Ayon>set COMPILEPLUGIN=

C:\Users\annat\Documents\Projects\Ayon>cmake -S . -B build -DDEV=0 -DJTRACE=0 -DCMAKE_BUILD_TYPE=Release
CMake Error: The source directory "C:/Users/annat/Documents/Projects/Ayon" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

C:\Users\annat\Documents\Projects\Ayon>cmake --build build --clean-first --config Release
Error: C:/Users/annat/Documents/Projects/Ayon/build is not a directory

C:\Users\annat\Documents\Projects\Ayon>cmake --install build
CMake Error: Error processing file: C:/Users/annat/Documents/Projects/Ayon/build/cmake_install.cmake
```
Sure it was as naive as running it directly from within developer console, but maybe we should add some sanity checks. But in next PR - just mentioning it here.


Also, the script are expecting that you will run them from specific directory - like `/scripts/build.bat` has to be run from within `/scripts` otherwise it will fail.

2024-05-24 12:50 UTC, antirotor reviewed
I've successfuly built resolver for houdini. Apart from the stuff from my previous comment, I think we can merge it. The only change I would do now is to unify names and the structure of make files - build scripts

1) Do we need to separete platfroms by directories? Isn't enough to have that separation on file level? `MayaWin/WinPy311Maya2025.cmake` vs `Maya/WinPy311Maya2025.cmake`

2) I would unify naming across hosts and platforms: for example `maya_2025-py311_win64.cmake`, `houdini_19.5-py29_linux.cmake` . Or something different, just that the order is the same.

2024-05-24 12:53 UTC, antirotor requested changes
see comments above

2024-05-27 13:40 UTC, Lyon-Rosenblatt-Ynput commented on src/AyonUsdResolver/CMakeLists.txt
> +#TODO posibly no need to link AyonCppApi for the Python target. needs testing
This TODO is gone now. I forgot to remove it.

2024-05-28 07:01 UTC, Lyon-Rosenblatt-Ynput commented
> COMPILEPLUGIN
1.
I believe the current separation is better than unifying them into one folder. 
My reason for that is that having all the resolvers inside a folder can make it hard to find things if you build, for eg 
- win, Alma9, Alma8, CentOs7, CentOsStream9, Ubunto, etc 
I also want to note: that we currently only support Houdini 19.5 and 20, and with the current separation, this already creates 4 files in the HouLinux folder; if we add 2 more versions, e.g. 20.5, and 21, we will end up with 8 files. if we now unify Windows and Linux foulders then we have 16 files, 8 of those files do not matter to you if you're only working on one platform at a time, and that's mostly the case; even I don't care for the Windows files when on Linux and the other way around. 
So, in the end, I don't see a disadvantage in having them separated the way they are right now, but I can see an annoyance in having them all bundled up. Do you have a reason for wanting that change? 

2.
I'm not sure if I'm following TBH. As I see it, the naming is unified ( {platform}{PythonVersoin}{SoftwareVersion} ). I personally avoid `.` and `-` in naming schemes as much as I can. We could add underscores between the parts of the name, but I don't know if that would be a big advantage. if you have a naming scheme you would like let me know what it is and why you would like it.

2024-05-28 14:03 UTC, antirotor commented on README.md
> +1. Currently, we only support Houdini and AyonUsd for building revolvers (other software packages and stand-alone setups will follow).
Maybe we should rephrase it (because of Maya and Unreal)?
```suggestion
1. Currently, we only support specific set of DCCs and their versions, and AyonUsd for building revolvers (other software packages and stand-alone setups will follow).

```

2024-05-28 14:30 UTC, merged