Create super-linter.yml
ynput/ayon-usd-resolver pull request #16
Opened 2024-05-21 13:55 UTC by antirotor

2024-07-09 08:22 UTC, Lyon-Rosenblatt-Ynput approved these changes

2024-08-28 08:16 UTC, BigRoy commented
This seems approved by Lyon, but still lingering for a while. Still relevant? If so, should we merge this?

2024-08-29 07:29 UTC, Lypsolon commented
lets not merge it right now. 
sorry i removed my approve for now because right now its hard to find the time to do extensive testing. 

i tryed implementing linting in some other Repo a short while back and it was havaly erroring. 
over all i very much belie we should do linting but only with one linter super linter by default turns out to lint with multiple linters and they do disagree some time. 

i vote for Black

2024-08-29 07:30 UTC, Lypsolon commented
@antirotor if you want you can assign it to me and i do testing etc for linting in the next epic ? 

or do you prefer having it before ?

2024-08-29 07:31 UTC, Lypsolon requested changes
[duplicate because of GH]
lets limit this to one linter

2026-02-20 12:26 UTC, BigRoy commented
We can probably close this @antirotor ? :) it's been forever.

2026-03-10 12:13 UTC, closed without merging

2026-03-10 12:13 UTC, antirotor commented
Noone wants nice linting. So sad.

2026-03-10 13:18 UTC, BigRoy commented
I want a good linter - but this PR wasn't in a mergable state anynore I figured :D