Feature/ay 1212 cache entetry struct replacment for cache pair
ynput/ayon-usd-resolver pull request #22
Opened 2024-07-15 12:16 UTC by Lypsolon

replace the cache pair system with a entity struct to allow for easy feature implementation in the future 

`this is a blocking pr for Pinning support as pinning support will use a cache invalidation mechanism`

2024-07-17 14:06 UTC, Lypsolon commented
This pr also includes the fix for the SDF_FORMAT_ARGS

[RES_FUNCS_REMOVE_SDF_ARGS()](https://github.com/ynput/ayon-usd-resolver/blob/1a762bab944d306a1dcd399803adac11cbe5c8e3/src/AyonUsdResolver/resolver.cpp#L101C41-L101C66)

And we are still unsure how this should be fixed correctly. 
Here is a chat about it on the Forums  https://forum.aousd.org/t/sdf-format-args-and-custom-ar-resolvers/1660/6

2024-07-17 15:19 UTC, antirotor requested changes
Just few typos. Can't test it so let's merge it and wait for more "testable" state of this feature.

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/resolverContextCache.h
> +         * so no acces will be granted to ayonCache or preCache for the scope of this function
```suggestion
         * so no access will be granted to ayonCache or preCache for the scope of this function
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/resolverContextCache.h
> +         * is enough space in the preCache and move the preCache if needed. this function is both locking and blocking
```suggestion
         * is enough space in the preCache and move the preCache if needed. This function is both locking and blocking
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/assetIdentDef.h
> +         * @return ture if you are allowed to modify the assetIdent false if modification is not allowed for what ever
```suggestion
         * @return true if you are allowed to modify the assetIdent, false if the modification is not allowed for what ever
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/assetIdentDef.h
> +         * @brief allows you to validate this assetIdent. this function will return while doing nothing if is_modifiable
```suggestion
         * @brief allows you to validate this assetIdent. This function will return while doing nothing if is_modifiable
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/assetIdentDef.h
> +         * @brief allows you to invalidate this assetIdent. it is not possible to invalidate an assetIdent that is not
```suggestion
         * @brief allows you to invalidate this assetIdent. It is not possible to invalidate an assetIdent that is not
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/assetIdentDef.h
> +         * @brief this function allows you to know if an given assetIdent's cache is still valid. this can be use full
```suggestion
         * @brief this function allows you to know if an given assetIdent's cache is still valid. This can be use full
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/assetIdentDef.h
> +         * @return bool: true if Neither m_resolvedAssetPath or m_assetIdentifier have any data in them
```suggestion
         * @brief can be used to know if given assetIdent has data in it
         *
         * @return bool: true if neither m_resolvedAssetPath or m_assetIdentifier have any data in them
```

2024-07-17 15:19 UTC, antirotor commented on src/AyonUsdResolver/assetIdentDef.h
> +         * @return false if assetIdent cant be modified (eg. is_valid)
```suggestion
         * @return false if assetIdent can't be modified (eg. is_valid)
```

2024-07-18 14:25 UTC, antirotor approved these changes

2024-07-18 14:25 UTC, merged