Feature/23 feature request pinn file loading
ynput/ayon-usd-resolver pull request #24
Opened 2024-07-24 08:47 UTC by Lypsolon

## Changelog Description

## Additional info

## Testing notes:

1. start with this step
2. follow this step

2024-08-09 06:37 UTC, Lypsolon commented
@dee-ynput and @BigRoy, I requested you because of the documentation part mainly. just FYI

2024-08-13 13:23 UTC, robin-ynput requested changes
Hey @Lypsolon, overall that looks good to me.
The cpp part reads fine, I had no trouble understanding your logic here.

One recommendation for the future, this could easily have been 3 separated PRs (easier to review):
- new cache logic feature implementation with dependencies update
- rework build script in Python
- documentation

2024-08-13 13:23 UTC, robin-ynput commented on Docs/Ayon_Docs/Dev_Docs.md
> +figure out what asset you want.
picky, correct me if I'm wrong but I'd suggest to rephrase it this way.
The resolver expects a valid  AYON URI, which needs to match that:
* scheme: "ayon"
* path: path to the product folder 
* query: product name, version and representation fixed to usd (with the different options).

![image](https://github.com/user-attachments/assets/49ca8b38-bfb1-4aa6-a6f1-e92cdcc53b70)

2024-08-13 13:23 UTC, robin-ynput commented on scripts/build.py
> +            os.environ[key] = val
is that a concern that you might not restore the env as-is upon script finished ?

2024-08-13 13:23 UTC, robin-ynput commented on scripts/build.py
> +        print("Last Selected Compile plgin is not the same as the current", compile_plugin, last_compile_plugin)
```suggestion
        print("Last Selected Compile plugin is not the same as the current, force clean", compile_plugin, last_compile_plugin)
```

2024-08-13 13:23 UTC, robin-ynput commented on scripts/build.py
> +    subprocess.run(command)
would recommend having `subprocess.run(command, check=True)` or `subprocess.check_call(command)` here and catch any potential issues.

2024-08-13 13:23 UTC, robin-ynput commented on src/AyonUsdResolver/config.h
> +#define ENABLE_STATICK_GLOBAL_CACHE_ENV_KEY "ENABLE_STATICK_GLOBAL_CACHE"
as mentioned if that's new I'd recommend to remove the "K" from static in those const.

2024-08-20 06:36 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +`ENABLE_STATICK_GLOBAL_CACHE`\
`<nOob alert>`
Refactored: 
And jap i typoed the env key,

2024-08-20 07:22 UTC, Lypsolon commented on scripts/build.py
> +            os.environ[key] = val
Do you mean resetting the Env variables to the state they used to be before we added our new env vars? 

Aka. removing all the --extra_env_vars from the running environment? 

I would say we can do that. I never had a problem keeping it dirty until now, and no one complained. (the terminal used for building is usually short-lived on my side)
but if some one wants that i can add it.

2024-08-20 07:36 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +the resolver how we use it and
I rewrote this sentence.
Because I'm not entirely sure what I wanted to say there.

2024-08-20 07:40 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +AyonCppApi.\
I added a short line of text to explain that a memory cache bypassed the resolver.

2024-08-20 08:19 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +### Asset Identifier / Behavior:
Sorry, but I don't quite understand what you mean. 
I guess you mean we should discuss how identification and communication are being made via a URI? and what the C++ API does.

2024-08-20 08:20 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +figure out what asset you want.
I didn't add a picture, but I took your bullet points and added the "old" data to them to expand the query parameter options a bit.

2024-08-20 08:23 UTC, Lypsolon commented on scripts/build.py
> +    subprocess.run(command)
I added the check=True, but no try-catch for now. 
I think the standard error will be enough for now + I was also unable to get any non-code error-related and I think it's enough when a Cmake error is just given to the dev?

2024-08-20 08:27 UTC, Lypsolon commented on src/AyonUsdResolver/config.h
> +#define ENABLE_STATICK_GLOBAL_CACHE_ENV_KEY "ENABLE_STATICK_GLOBAL_CACHE"
jup corrected

2024-08-20 09:44 UTC, Lypsolon commented
> Hey @Lypsolon, overall that looks good to me. The cpp part reads fine, I had no trouble understanding your logic here.



> One recommendation for the future, this could easily have been 3 separated PRs (easier to review):
> 
>     * new cache logic feature implementation with dependencies update
> 
>     * rework build script in Python
> 
>     * documentation

I will split it into multiple ones next time. point taken ;-)

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +`resolver = Ar.GetResolver()` there are multiple ways to get access to an
```suggestion
`resolver = Ar.GetResolver()` there are multiple ways to get access to a
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +in short pinning support allows you to load a pinning File and disconnect the
```suggestion
In short _pinning support_ allows you to load a pinning file and disconnect the
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +avoid impacting the server performance.
```suggestion
:::note Why use pinning?
When running a resolver on a farm with many workers (render nodes) 
you might not want them all to call the Ayon server to avoid impacting 
the server performance. This is because USD Resolvers will resolve paths
one by one, potentially resulting in many calls.
:::
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +you don't want to activate the feature.
Could you explain more on this? Not sure why or why not?

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +this is a path to the pinning file.
```suggestion
This is a path to the pinning file.
```

Is this always a full path? If so, should it elaborate on that? if it supports relative paths, then "relative" to what? :)

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +when running the resolver against the AYON server the CppApi will query the
```suggestion
When running the resolver against the AYON server the CppApi will query the
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +`Get Project Site Roots` endpoint and get a Dict[str,str] of
```suggestion
`Get Project Site Roots` endpoint and get a `Dict[str,str]` of
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +stage = Usd.Stage.Open(pinning_file_json["ayon_pinning_data_entry_sceene"])
Typo `sceene`?

Also, why do we define the scene file in the JSON?

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +`ayon_pinning_data_entry_sceene`.\
Typo.
```suggestion
`ayon_pinning_data_entry_scene`.\
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +local path the resolver wont be able to resolve.
I don't understand this :)

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +this does not work if you disconnected the Global cache from your resolver.
```suggestion
This does not work if you disconnected the Global cache from your resolver.
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +individual cached entry.\
```suggestion
`context.deleteFromCache(AssetIdentifier)` delete an individual cached entry.
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +where added by this resolver.\
```suggestion
`context.clearCache()` clear the connected cache. 

:::note
It is important to understand that by default a Resolver will be connected to the global cache
and this call will delete all entries in the global cache not just the ones that
where added by this resolver.
:::
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +context.deleteFromCache(AssetIdentifier)
```suggestion
asset_identifier: str="ayon://{ProjectName}/{path/to/ayon/folder}?product={FileName}&version=latest&representation=usd"
context.deleteFromCache(asset_identifier)
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +**Naming BuildPluingins**
```suggestion
**Naming Build Plugins**
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +BuildPluingins Naming schema is as follows:
```suggestion
Build Plugins Naming schema is as follows:
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +PlatfromName options = {Win, Linux, Mac, specific Os Name}
```suggestion
PlatformName options = {Win, Linux, Mac, specific Os Name}
```

2024-08-20 10:16 UTC, BigRoy commented on Docs/Ayon_Docs/Dev_Docs.md
> +**Dependencys**
```suggestion
**Dependencies**
```

2024-08-20 10:16 UTC, BigRoy commented on src/AyonUsdResolver/cache/resolverContextCache.h
> +        ~pinningFileHanlder() = default;
```suggestion
class pinningFileHandler {
    public:
        pinningFileHandler(const std::string &pinningFilePath,
                           const std::unordered_map<std::string, std::string> &rootReplaceData);
        ~pinningFileHandler() = default;
```
Typos. Of course also check other usages of these.

2024-08-20 10:16 UTC, BigRoy commented on src/AyonUsdResolver/cache/resolverContextCache.cpp
> +pinningFileHanlder::pinningFileHanlder(const std::string &pinningFilePath,
```suggestion
pinningFileHandler::pinningFileHandler(const std::string &pinningFilePath,
```

2024-08-20 10:16 UTC, BigRoy commented on src/AyonUsdResolver/cache/resolverContextCache.cpp
> +pinningFileHanlder::getAssetData(const std::string &resolveKey) {
```suggestion
pinningFileHandler::getAssetData(const std::string &resolveKey) {
```

2024-08-20 10:16 UTC, BigRoy commented on src/AyonUsdResolver/cache/resolverContextCache.cpp
> +        return this->m_pinningFileHanlder->getAssetData(assetIdentifier);
```suggestion
        return this->m_pinningFileHandler->getAssetData(assetIdentifier);
```
Haha, you can likely best refactor this in your IDE all at once instead of me trying to find them all here... :)

2024-08-20 12:15 UTC, Lypsolon commented on src/AyonUsdResolver/cache/resolverContextCache.h
> +        ~pinningFileHanlder() = default;
Fixed via a commit.

2024-08-20 12:15 UTC, Lypsolon commented on src/AyonUsdResolver/cache/resolverContextCache.cpp
> +pinningFileHanlder::getAssetData(const std::string &resolveKey) {
Fixed via a commit.

2024-08-20 12:21 UTC, Lypsolon commented on src/AyonUsdResolver/cache/resolverContextCache.cpp
> +pinningFileHanlder::pinningFileHanlder(const std::string &pinningFilePath,
Fixed via a commit.

2024-08-20 12:21 UTC, Lypsolon commented on src/AyonUsdResolver/cache/resolverContextCache.cpp
> +        return this->m_pinningFileHanlder->getAssetData(assetIdentifier);
Fixed via a commit.

2024-08-20 12:28 UTC, Lypsolon commented on Docs/Ayon_Docs/Admin_Docs.md
> +TF_DEBUG:
I changed the text to clarify that we deliver two debug variables with the resolver. I also linked Luca Shellers debugging section of the usd survival guide so that people can find all the other debug variables generally available on USD.

2024-08-20 12:44 UTC, BigRoy commented on Docs/Ayon_Docs/Admin_Docs.md
> +    crazy.
```suggestion
  - The standards for the AYON Usd Resolver are `AYONUSDRESOLVER_RESOLVER`
    `AYONUSDRESOLVER_RESOLVER_CONTEXT` they can be used to get more detailed
    information about the resolver's operations. It is not advised to have these enabled
    outside of debugging as it will be very verbose and may have a big impact 
    on performance.
```

2024-08-20 12:44 UTC, BigRoy commented on Docs/Ayon_Docs/Admin_Docs.md
> +  - there are more optional debug variables that exist in Usd outside of the
```suggestion
  - There are more optional debug variables that exist in Usd outside of the
```

2024-09-11 07:16 UTC, Lypsolon commented on Docs/Ayon_Docs/Admin_Docs.md
> +TF_DEBUG:
im gonna resolve this conversation (just for organisation) 
if you want more please request it on the GH Pages branch. 

PS: im a also gonna move the 2 docs files over to the GH pages branch and remove it from here to keep shrink down the PR.

2024-09-11 10:37 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +AyonCppApi.\
i belive this is done so im gonna close it. 
PS: im moving the issues over to the docs branch just so you know if you want to open it again.

2024-09-11 10:40 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
moved to https://github.com/ynput/ayon-usd-resolver/pull/25#issuecomment-2343281677

2024-09-11 10:40 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +local path the resolver wont be able to resolve.
https://github.com/ynput/ayon-usd-resolver/pull/25#issuecomment-2343280276

2024-09-11 10:41 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +stage = Usd.Stage.Open(pinning_file_json["ayon_pinning_data_entry_sceene"])
move to 
https://github.com/ynput/ayon-usd-resolver/pull/25#issuecomment-2343280605

2024-09-11 10:41 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +you don't want to activate the feature.
moved to 
https://github.com/ynput/ayon-usd-resolver/pull/25#issuecomment-2343280880

2024-09-11 10:42 UTC, Lypsolon commented on scripts/build.py
> +            os.environ[key] = val
im gonna close this for now as it will be adressed with the Ayon Automator change. 
Hope that okay.

2024-09-11 10:44 UTC, Lypsolon commented on Docs/Ayon_Docs/Dev_Docs.md
> +### Asset Identifier / Behavior:
not sure if still valid. 
but also moved over to the other branch 
https://github.com/ynput/ayon-usd-resolver/pull/25#issuecomment-2343288296

2024-09-13 08:40 UTC, merged