implemented ayon automator as the Build Controle System
ynput/ayon-usd-resolver pull request #36
Opened 2024-10-01 14:44 UTC by Lypsolon

## Changelog Description
this PR adds the Ayon Automator and Creates a few Different Build Stages make Ci and Developer Experience Easyer. 

you can eighter set the Varaibles as per Json Sceema or use the Recomended way with a build config YAML. 

build_config.yaml
```yaml
# AyonUsd
AyonUsd_Linux: 
  COMPILEPLUGIN: "AyonUsdLinux/AyonUsd23_5_Py39_Linux"
  AyonUsdRoot: "$HOME/Documents/GitHub/Lyonh/ayon_usd_files/usd-24.03_linux_py39/24.03/"

AyonUsd_Windows: 
  COMPILEPLUGIN: "AyonUsdWin/AyonUsd23_5_Py39_Win"
  AyonUsdRoot: "C:\\Users\\ynput\\Documents\\GitRepos\\usd-24.03_win64_py39\\usd-24.03_win64_py39\\23.04"
```
the automator allows Define all build targets in the build conf file in yaml format. 
then you can use an Target option to specify what you want to build (Default is all) 

build conf Spec
```
RUN_NAME: 
  COMPILEPLUGIN: "<Build Plugin Name"
  // List of Env Variables for the Build Plugin
  <Key>: "<Val>"
```
in the end all variables under the Run name will be used as Env variables. 

## Additional info

## Testing notes:

1. start with this step
2. follow this step

2024-10-01 22:02 UTC, BigRoy commented
This is best reviewed by someone else - I know too little about this to say anything sensible. I did take a minute to just cleanup the PR description itself.

2024-10-04 11:39 UTC, antirotor requested changes
some typos, not sure if I've got all in the suggestions

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +parrallel_limit = threading.Semaphore(cmd_args.Parallel)
```suggestion
parallel_limit = threading.Semaphore(cmd_args.Parallel)
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +def remove_all_build_foulders():
```suggestion
def remove_all_build_folders():
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +    zip_inner_foulder_path = os.path.join(temp_dir_for_zip, zip_inner_foulder_name)
```suggestion
    zip_inner_folder_name = os.path.basename(zip_path)
    zip_inner_folder_path = os.path.join(temp_dir_for_zip, zip_inner_folder_name)
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +    os.makedirs(zip_inner_foulder_path)
```suggestion
    os.makedirs(zip_inner_folder_path)
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +    shutil.copytree(resolver_source_path, zip_inner_foulder_path, dirs_exist_ok=True)
```suggestion
    shutil.copytree(resolver_source_path, zip_inner_folder_path, dirs_exist_ok=True)
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +        parrallel_limit.acquire()
```suggestion
        parallel_limit.acquire()
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +        parrallel_limit.release()
```suggestion
        parallel_limit.release()
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +        raise ValueError(f"Config not Valid {e}, data:{build_config}")
```suggestion
        raise ValueError(f"Config not Valid {e}, data:{build_config}") from e
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +    remove_all_build_foulders()
```suggestion
    remove_all_build_folders()
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
> +zip_package_stage.addArtefactFoulder(
```suggestion
zip_package_stage.addArtefactFolder(
```

2024-10-04 11:39 UTC, antirotor commented on Project.py
this could make use of some docstrings :)

2024-10-04 12:47 UTC, MustafaJafar commented on Project.py
> +zip_package_stage.addArtefactFoulder(
this also requires to rename https://github.com/ynput/ayon-automator/blob/f323086ff197e89b794beb40732885869b84ffbd/AyonCiCd/Project.py#L508

2024-10-04 12:48 UTC, Lypsolon commented on Project.py
done.

2024-10-04 13:13 UTC, MustafaJafar commented
This method has to be renamed to `addArtefactFolder` https://github.com/ynput/ayon-automator/blob/f323086ff197e89b794beb40732885869b84ffbd/AyonCiCd/Project.py#L508

--- 

when running the following command in cmd, I faced an error
```
python Project.py --runStageGRP "Build and Zip" --setVars {\"BuildConf\":\"build_conf.yaml\"}
```
it was solved by adding this argument to the following function `type=json.loads`, [reference](https://stackoverflow.com/questions/7625786/type-dict-in-argparse-add-argument)

https://github.com/ynput/ayon-automator/blob/a595cab5532b30df538cd328d2187a830a94e202/AyonCiCd/Project.py#L313-L318

and then change this line https://github.com/ynput/ayon-automator/blob/a595cab5532b30df538cd328d2187a830a94e202/AyonCiCd/Project.py#L23
to 
```
extra_env_var_dict = values
```

2024-10-04 13:22 UTC, MustafaJafar commented
Also, here are my testing steps in cmd: 
```
git checkout 20-feature-implement-ayonautomater-for-build-and-testing
git submodule update --init --recursive
python Project.py --setup
# Create build_conf.yaml  manually, I don't know what to put inside it.
python Project.py --runStageGRP "Generate Release" --setVars {\"BuildConf\":\"build_conf.yaml\"}
```

2024-10-04 13:25 UTC, Lypsolon commented
> traceback: <traceb

nice an windows error i love it. 
welp time to find out if there are windows and linux differences again. 
Manny thanks for testing.

2024-10-04 13:29 UTC, Lypsolon commented
> Also, here are my testing steps in cmd: and, I 've `build_conf.yaml` file in the `ayon-usd-resolver` repo, I don't know what to put inside it.
> 
> ```
> git checkout 20-feature-implement-ayonautomater-for-build-and-testing
> git pull origin 20-feature-implement-ayonautomater-for-build-and-testing
> git submodule update --init --recursive
> python Project.py --setup
> python Project.py --runStageGRP "Generate Release" --setVars {\"BuildConf\":\"build_conf.yaml\"}
> ```

the build_conf.yaml needs to look like this.  

```
# the name for the entry needs to have the target platform.system() Linux, Windows 

# AyonUsd
AyonUsd_Linux: 
  COMPILEPLUGIN: "AyonUsdLinux/AyonUsd23_5_Py39_Linux"
  AyonUsdRoot: "$HOME/Documents/GitHub/Lyonh/ayon_usd_files/usd-24.03_linux_py39/24.03/"

AyonUsd_Windows: 
  COMPILEPLUGIN: "AyonUsdWin/AyonUsd23_5_Py39_Win"
  AyonUsdRoot: "C:\\Users\\ynput\\Documents\\GitRepos\\usd-24.03_win64_py39\\usd-24.03_win64_py39\\23.04"


..... more Target Configs 
```

you can just put ayon usd compile into it to limit the work that gets done (if you have multiple "targets" the system will compile them in parallel but with the same system so its not needed for testing )

for reference you yaml can look like this. and the AyonUsdRoot needs to point to a valid usd lib. an easy way to get one is to just run the ayon usd addon and point to the downloaded usd lib in there. (PS: the usd lib might be in a second sub foulder aka /ayon-usd/downloads/usdLibName/v24.08/ <- and here you find the actual lib. if there is no version number folder just ignore this text) 
```
AyonUsd_Windows: 
  COMPILEPLUGIN: "AyonUsdWin/AyonUsd23_5_Py39_Win"
  AyonUsdRoot: "C:\\Users\\ynput\\Documents\\GitRepos\\usd-24.03_win64_py39\\usd-24.03_win64_py39\\23.04"
```

2024-10-04 14:13 UTC, MustafaJafar commented on .gitignore
> +Ayon_Usd_Resolver_cicd/
What about gitignoring `build_conf.yaml`. I like to have it in my repo clone.
```suggestion
Ayon_Usd_Resolver_cicd/
build_conf.yaml
```

2024-10-04 14:19 UTC, MustafaJafar commented on .gitignore
> +Ayon_Usd_Resolver_cicd/
the conf file can have any name so it won't make much sense to have it like this.

2024-10-04 14:27 UTC, MustafaJafar commented
I've pulled the latest commits and it started working. 
Here's the next error 😅 
```
----------------------------------- __del__() -----------------------------------
("Finished Execution with code:1, {'Cmake': ['Error at "
 'build/AyonUsd_Windows/src/AyonUsdResolver/cmake_install.cmake:55 (file):\\n  '
 'file INSTALL cannot find\\n  '
 '"E:/Ynput/ayon-usd-resolver/build/AyonUsd_Windows/src/AyonUsdResolver/Release/ayonUsdResolver.dll":\\n  '
 'File exists.\\nCall Stack (most recent call first):\\n  '
 "build/AyonUsd_Windows/cmake_install.cmake:47 (include)']}",)
--------------------------------------------------------------------------------

Exception ignored in: <function Project.__del__ at 0x000002154A9418B0>
Traceback (most recent call last):
  File "E:\Ynput\ayon-usd-resolver\automator\AyonCiCd\Project.py", line 193, in __del__
SystemExit: 1
```

2024-10-04 15:03 UTC, MustafaJafar commented
Hey,
Here are step by step mini guide to test this PR. I think this guide can be useful for documenting how to build the resolver from [ayon-usd-resolver](https://github.com/ynput/ayon-usd-resolver) using the CI tools featured/enhanced in this PR.

## Intro
This PR adds/enhances the automation to build the available target within `Ayon_Usd_Resolver_cicd` folder. 
It'd be better to download the USD build from our [LakeFs Repo](https://lake.ayon.cloud). we provide two builds one for linux and one for windows. find them [here](https://lake.ayon.cloud/repositories/ayon-usd/objects?ref=main&path=AyonUsdBin%2F).

personally, I downloaded `usd-24.03_windows_py39.zip` as I'm on windows. 

## Testing Steps
1. Create your `build_conf.yaml`. you can name it what you want. personally, I added it in my `ayon-usd-resolver` clone
2. Specify desired targets to build in your `build_conf.yaml`. Personally, I'm going with `AyonUsd_Windows` and `Houdini195_Py39_Windows`
    ```yaml
    # AYON
    AyonUsd_Windows: 
    COMPILEPLUGIN: "AyonUsdWin/AyonUsd23_5_Py39_Win"
    AyonUsdRoot: "H:\\USDROOT\\usd-24.03_win64_py39\\23.04"  # path to the downloaded USD build.


    # Houdini
    Houdini195_Py39_Windows:
    COMPILEPLUGIN: "HouWin/Houdini195_Py39_Win"
    HFS: "C:\\Program Files\\Side Effects Software\\Houdini 19.5.805"  # path to my Houdini 19.5.805 install directory.
    ```
3. Checkout the correct branch, pull updates and update the submodules
    ```
    git checkout 20-feature-implement-ayonautomater-for-build-and-testing
    git pull origin 20-feature-implement-ayonautomater-for-build-and-testing
    git submodule update --init --recursive
    ```
4. Setup & Build
    ```
    python Project.py --setup
    python Project.py --runStageGRP "Generate Release" --setVars {\"BuildConf\":\"build_conf.yaml\"}
    ```

2024-10-04 15:03 UTC, Lypsolon commented
> I've pulled the latest commits and it started working. Here's the next error 😅
> 
> ```
> ----------------------------------- __del__() -----------------------------------
> ("Finished Execution with code:1, {'Cmake': ['Error at "
>  'build/AyonUsd_Windows/src/AyonUsdResolver/cmake_install.cmake:55 (file):\\n  '
>  'file INSTALL cannot find\\n  '
>  '"E:/Ynput/ayon-usd-resolver/build/AyonUsd_Windows/src/AyonUsdResolver/Release/ayonUsdResolver.dll":\\n  '
>  'File exists.\\nCall Stack (most recent call first):\\n  '
>  "build/AyonUsd_Windows/cmake_install.cmake:47 (include)']}",)
> --------------------------------------------------------------------------------
> 
> Exception ignored in: <function Project.__del__ at 0x000002154A9418B0>
> Traceback (most recent call last):
>   File "E:\Ynput\ayon-usd-resolver\automator\AyonCiCd\Project.py", line 193, in __del__
> SystemExit: 1
> ```

yes many thanks. 
i got the error too and it was a change in the ayon cpp api i forgot an target include while changing to target cmake. 

i just updated it and it should work now i hope. 

if its not that can you upload the file Ayon_Usd_Resolver_cicd/artefacts/Build Release.txt ?

2024-10-04 15:56 UTC, MustafaJafar commented
I've updated everything and I didn't hit any errors.
Here's my [Build Release.txt](https://github.com/user-attachments/files/17261023/Build.Release.txt)

Also, I can find the created zip package `ayon-usd-resolver\Ayon_Usd_Resolver_cicd\artefacts\Zip_Bin_Package_Artefacts\AyonUsdResolverBin.zip` which contains the two plugins specified in my `build_conf.yaml`.
![image](https://github.com/user-attachments/assets/afa7b6b9-fcc4-48df-99fb-8d717b8d86ff)

2024-10-08 13:02 UTC, antirotor approved these changes

2024-10-08 21:23 UTC, MustafaJafar approved these changes
It works on windows.

2024-10-09 06:53 UTC, Lypsolon commented
> It works on windows. For documentation purposes, here are the steps I followed to run it on windows [#36 (comment)](https://github.com/ynput/ayon-usd-resolver/pull/36#issuecomment-2393916204)

oh yeah i should fix the docs my bad. 
one moment

2024-10-09 11:43 UTC, merged